const ERR_STATUS_BAD_REQUEST = 400;
const ERR_STATUS_AUTH = 401;
const ERR_STATUS_NOT_FOUND = 404;
const ERR_STATUS_DEFAULT = 500;

module.exports = {
  ERR_STATUS_BAD_REQUEST, ERR_STATUS_NOT_FOUND, ERR_STATUS_DEFAULT, ERR_STATUS_AUTH,
};
